### ISSUE TITLE
[Bug] Can't login

### ISSUE THREAD

**Issue by mbarberot** [negue/HabitRPG-Metro#11]
I tried from both "Login with Username & Password" and "Login with UserID & API-Token" and I always have this error :
```
Please Check your UserID & API-Token.
Could not convert string to DateTime: 15/12.
Path 'date', line 1, position 73069
```

My UserId & API-Token are ok : I finally copied/pasted them with the QRCode from https://habitrpg.com/#/options/settings/api

**Comment by negue** [comment]
```Could not convert string to DateTime: 15/12.``` tells me that it can't parse your json data, although I have fixed all possible json errors ... could you tell me what Version you have installed?

If its 1.4 you should see a button (under the error) which can send the anonymized data to me :)
If not, please check for an update in the store.


Maybe I should change the error messages a bit^^

**Comment by mbarberot** [comment]
I just reinstalled it this afternoon from the store, but I don't have this button.
I'll try to update.

**Comment by negue** [comment]
If there is still no button, you could follow this (https://github.com/negue/HabitRPG-Metro/blob/master/getAnonymizedJson.md) to get the anonymized data

**Comment by mbarberot** [comment]
Still no update available. 
[Here is the anonymized json](https://gist.github.com/mbarberot/d279875d6d6451ca3f87)

**Comment by mbarberot** [comment]
@negue so ?

**Comment by negue** [comment]
@mbarberot  Sorry for the long repsonse pause, had to reinstall my Visual Studio ..:/


I can hopefully take a look at it later today, after that I'll post my test results.

In the meantime, are you on Tablet / Phone? 8.1 or 10?

**Comment by mbarberot** [comment]
Ok ;-)
I'm on Windows Phone 8.1

**Comment by negue** [comment]
@mbarberot yep this is a bug , the date field will hunt me for ever... :D, havent found a solution yet, but hopefully tomorrow, I'll post again once I have a running solution

**Comment by negue** [comment]
@mbarberot I've uploaded a new Version (1.4.0.1) yesterday should be already in the store, could you update test if it works now?

**Comment by mbarberot** [comment]
Updated to 1.4.0.1
I can login now, thanks !
