### ISSUE TITLE
windows 8 tablet

### ISSUE THREAD

**Issue by ZigCubed** [negue/HabitRPG-Metro#5]
I just started using this and love it.
However I just bought a windows 8 tablet and I would like to see it so that the site is responsive. The screen size is 7 inches and although I can scroll, it would be nice if you could have the option to view all the cards in 1 window.

Thanks

**Comment by negue** [comment]
Sorry it took so long. I've implemented that view setting! Currently testing all possible bugs. 

And a new release of the Tablet / Desktop Version will be pushed at the end of the week.
